name: Linux

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Tag name for release"
        required: false
        default: nightly

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

jobs:
  tagname:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.tag.outputs.tag }}
    steps:
      - id: vars
        shell: bash
        run: echo "sha_short=${GITHUB_SHA::7}" | tee -a $GITHUB_OUTPUT

      - if: github.event_name == 'workflow_dispatch'
        run: echo "TAG_NAME=${{ github.event.inputs.tag_name }}" | tee -a $GITHUB_ENV

      - id: tag
        run: echo "tag=$TAG_NAME" | tee -a $GITHUB_OUTPUT

  linux:
    runs-on: ubuntu-latest
    needs: tagname
    env:
      RELEASE_TAG_NAME: ${{ needs.tagname.outputs.tag_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Build binary packages (with output)
        run: |
          docker buildx create --driver=docker-container --use
          timeout --preserve-status --foreground 15m bash -c '
            while true; do echo "Still building..."; sleep 60; done &
            docker buildx bake --pull ubuntu-focal-binary
          '

      - name: Gzip
        run: |
          mkdir Lapce
          cp ./target/linux_amd64/lapce Lapce/
          tar -zcvf ./lapce-linux-amd64.tar.gz Lapce

          rm -rf Lapce

          mkdir Lapce
          cp ./target/linux_arm64/lapce Lapce/
          tar -zcvf ./lapce-linux-arm64.tar.gz Lapce

      - name: Fetch dependencies
        run: cargo fetch --locked

      - name: Vendor dependencies
        run: |
          cargo vendor --frozen > ./vendor-config.toml
          mv ./vendor-config.toml ./vendor/
          tar -zcf vendor.tar.gz ./vendor/

      - uses: actions/upload-artifact@v4
        with:
          name: lapce-linux
          path: |
            ./lapce-linux-*.tar.gz
            ./vendor.tar.gz
          retention-days: 1
